name: "Nix Flake Check"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Check Nix flake Nixpkgs inputs
      uses: DeterminateSystems/flake-checker-action@main

    - uses: cachix/install-nix-action@v31        
    
    - uses: DeterminateSystems/magic-nix-cache-action@main
    
    - name: Run nix flake check
      run: nix flake check
